### ISSUE TITLE
ZIO test migration

### ISSUE THREAD

**Issue by ioleo** [zio/zio-macros#46]
In #45 we've migrated to ZIO Test, however some of the test cases that previously worked now fail.
The implementation if delegate/mix has not changed, so either previous tests did a poor job at catching the bug or there is not bug and some ZIO Test implementation details affect the compilation/runtime result in these cases.

Aggregate issue to track progress of following:
- [x] #47 **DelegateSpec** *should handle methods with same name but different signatures* **case 1** does not compile on 2.11
- [x] #48 **DelegateSpec** *should handle methods with same name but different signatures* **case 2** does not compile on 2.11
- [x] #49 **MixSpec** *should overwrite methods defined on both instances with the second* fails on 2.11
- [x] #50 **MixSpec** *should allow mixing of traits* does not compile on 2.11
